from random import randint
from .nomes import lista_nomes
from .models import UF_CHOICES

lista_logradouro = ['Rua', 'Avenida', 'Praça']

lista_empresas = [
    'Walmart',
    'ExxonMobil',
    'Google',
    'Microsoft',
    'PetroChina',
    'Johnson',
    'Novartis',
    'China',
    'Apple',
    'General',
    'Nestlé',
    'Toyota',
    'Hoffmann',
    'Facebook',
    'Procter',
    'Pfizer',
    'Alibaba',
    'Verizon',
    'Chevron',
    'Anheuser',
    'Royal',
    'Samsung',
    'Oracle',
    'Walt',
    'Tencent',
    'Coca',
    'Amazon',
    'AT',
    'Merck',
    'IBM',
    'The',
    'Intel',
    'Gilead',
    'Comcast',
    'Pepsi',
    'Novo',
    'Cisco',
    'Sanofi',
    'Unilever',
    'Volkswagen',
    'Bayer',
    'BHP',
    'Amgen',
    'TSMC',
    'CP',
    'Total',
    'BP',
    'Actavis',
    'CVS',
    'Philip',
    'Qualcomm',
    'UHG',
    'GlaxoSmithKline',
    'Medtronic',
    'Bristol',
    'Schlumberger',
    'United',
    'Boeing',
    '3M',
    'L',
    'Daimler',
    'Inditex',
    'Biogen',
    'Altria',
    'British',
    'Union',
    'Siemens',
    'McDonald',
    'AbbVie',
    'Walgreens',
    'Celgene',
    'BASF',
    'Kinder',
    'AmBev',
    'LVMH',
    'SAP',
    'United',
    'AstraZeneca',
    'Vodafone',
    'Nike',
    'SABMiller',
    'ConocoPhillips',
    'Tata',
    'Grupo',
    'Telefónica',
    'Nippon',
    'Lowe',
    'Starbucks',
    'Twenty',
    'NTT',
    'Abott',
    'Time',
    'eBay',
    'SoftBank',
    'Diageo',
    'Valeant',
    'Costco',
    'Lockheed',
    'DuPont',
    'Naspers',
    'Japan',
    'ES',
    'China',
    'ENI',
    'Saudi',
    'China',
    'Colgate',
    'Ford',
    'Reckitt',
    'KDDI',
    'General',
    'Danaher',
    'Priceline',
    'Mondelēz',
    'Texas',
    'Hutchison',
    'Gazprom',
    'Hennes',
    'Honda',
    'Telstra',
    'Hewlett',
    'Statoil',
    'Occidental',
    'Dow',
    'Glencore',
    'BT',
    'Canadian',
    'Duke',
    'Monsanto',
    'Thermo',
    'McKesson',
    'Target',
    'FANUC',
    'Kraft',
    'Airbus',
    'SingTel',
    'EMC',
    'ABB',
    'Caterpillar',
    'Engie',
    'Henkel',
    'TJX',
    'Grid',
    'Shire',
    'Continental',
    'Canon',
    'Next',
    'FedEx',
    'Nissan',
    'Regeneron',
    'Schneider',
    'América',
    'Rosneft',
    'APMoller',
    'ASML',
    'General',
    'Liberty',
    'SAIC',
    'Électricité',
    'Air',
    'Heineken',
    'Salesforce',
    'Las',
    'Jardine',
    'Danone',
    'Walmex',
    'Suncor',
    'Richemont',
    'Time',
    'Phillips66',
    'DirecTV',
    'Anadarko',
    'Lyondell',
    'Citic',
    'Imperial',
    'BG',
    'Orange',
    'Enel',
    'Hon',
    'Reliance',
    'Yahoo',
    'Dominion',
    'Wellpoint',
    'CCC',
    'Iberdrola',
    'Ericsson',
    'ONG',
    'ITG',
    'Fast',
    'Denso',
    'Southern',
    'K',
    'Petrobras',
    'Infosys',
    'Enbridge',
    'Takeda',
    'CRG',
    'LUKoil',
    'JardineS',
    'Hyundai',
    'Cognizant',
    'Emerson',
    'Nvidia',
    'Atlas',
    'CJR',
    'Linde',
    'Astellas',
    'Seven',
    'Willians',
    'Kroger',
    'Post',
    'Baxter',
    'Aetna',
    'Delta',
    'CSCE',
    'Hermes',
    'Hanergy',
    'Wesfarmers',
    'Kweichow',
    'Illinois',
    'American',
    'Adobe',
    'Reynolds',
    'Unicom',
    'Reed',
    'Alexion',
    'BCE',
    'NetEase',
    'Stryker',
    'Kweichow',
    'Praxair',
    'Yum',
    'Christian',
    'Ecolab',
    'CSR',
    'Norfolk',
    'Raytheon',
    'Activision',
    'General',
    'JC',
    'Sands',
    'Cigna',
    'CRC',
    'China',
    'AB',
    'Vivendi',
    'Saudi',
    'Vinci',
    'Sun',
    'CSL',
    'Imperial',
    'CN',
    'Keyence',
    'Hitachi',
    'Halliburton',
    'Twitter',
    'CSX',
    'Valero',
    'Avago',
    'VF',
    'Panasonic',
    'Bridgestone',
    'APC',
    'Femsa',
    'Reuters',
    'EJR',
    'Sony',
    'Murata',
    'Syngenta',
    'Northrop',
    'Eaton',
    'HCA',
    'Pernod',
    'MTN',
    'Transcanada',
    'CPR',
    'Fresenius',
    'Swisscom',
    'PPG',
    'Telenor',
    'Luxottica',
    'E',
    'Becton',
    'Southwest',
    'Archer',
    'Cardinal',
    'Precision',
    'Deere',
    'CSI',
    'WPP',
    'Tesco',
    'Safran',
    'SK',
    'Hilton',
    'Micron',
    'TE',
    'Mylan',
    'Corning',
    'Shin',
    'Exelon',
    'Vertex',
    'CYP',
    'Compass',
    'MMC',
    'Woolworths',
    'Marathon',
    'CBS',
    'Viacom',
    'AM',
    'Baker',
    'LBrands',
    'AEP',
    'Sherwin',
    'Humana',
    'Intuit',
    'Illumina',
    'Sempra',
    'Vale',
    'Surgutne',
    'Telia',
    'Potash',
    'Fujifilm',
    'Daqin',
    'MTR',
    'Rolls',
    'Renault',
    'Numericable',
    'Altice',
    'KEP',
    'Philips',
    'Tata',
    'Mitsubishi',
    'KAO',
    'Broadcom',
    'UC',
    'T',
    'Pg',
    'NXP',
    'Netflix',
    'Cummins',
    'Electronic',
    'Cerner',
    'British',
    'Organização',
    'Repsol',
    'Volvo',

    'Nestlé',
    'Anheuser-Busch',
    'Roche',
    'Rdsa',
    'Novartis',
    'HSBC',
    'Unilever Nv-Cva',
    'Unilever Plc',
    'Total Sa',
    'British American Tobacco',
    'Sap Se',
    'Inditex',
    'Sanofi',
    'Siemens Ag-Reg',
    'BP Plc',
    'Lvmh Moet Hennessy Louis Vui',
    'Medtronic Plc',
    'Real',
    'Glaxosmithkline Plc',
    'Novo Nordisk A / S-B',
    'Bayer Ag-Reg',
    'Banco Santander',
    'Basf Se',
    'Allianz Se-Reg',
    'Deutsche Telekom Ag-Reg',
    'BNP Paribas',
    'Volkswagen Ag',
    'Accenture Plc-Cl A',
    'Ações registradas da Daimler Ag',
    'Astrazeneca Plc',
    'Rio Tinto Ltd',
    'Rio Tinto Plc',
    'Diageo Plc',
    'Vodafone Group Plc',
    'Reckitt Benckiser Group Plc',
    'Chubb Ltd',
    'Ubs Group Ag-Reg',
    'Axa Sa',
    'Ing Groep Nv',
    'Lloyds Banking Group Plc',
    'Bayerische Motoren Werke Ag',
    'Airbus Se',
    'Eni Spa',
    'Asml Holding Nv',
    'Telefonica Sá',
    'Glencore Plc',
    'Statoil Handle',
    'Prudential Plc',
    'Henkel Ag & Co Kgaa Vorzug',
    'Hermes International',
    'Heineken Nv',
    'Abb Ltd-Reg',
    'BBVA',
    'Merck Kgaa',
    'National Grid Plc',
    'Enel Spa',
    'Imperial Brands Plc',
    'Nordea Bank Ab',
    'Vinci Sa',
    'Iberdrola Sá',
    'Barclays Plc',
    'Cie Financiere Richemont-Reg',
    'Danone',
    'Intesa Sanpaolo',
    'Air Liquide Sa',
    'Fresenius Se & Co Kgaa',
    'Schneider Electric Se',
    'Christian Dior Se',
    'Syngenta Ag-Reg',
    'Continental Ag',
    'Atlas Copco Ab-A Shs',
    'Deutsche Post Ag-Reg',
    'Relx Nv',
    'Relx Plc',
    'Hennes e Mauritz Ab-B Shs',
    'laranja',
    'Zurich Insurance Group Ag',
    'Bt Group Plc',
    'Adidas Ag',
    'Societe Generale Sá',
    'Credit Agricole Sa',
    'Nxp Semiconductors Nv',
    'Grupo Royal Bank Of Scotland',
    'Lafargeholcim Ltd-Reg',
    'Ap Moller-Maersk A / S-B',
    'Kering',
    'Engie',
    'Registrado no Deutsche Bank Ag',
    'Danske Bank A / S',
    'Investidor Ab-B Shs',
    'Unicredit Spa',
    'Safran Sa',
    'Pernod Ricard Sa',
    'Swiss Re Ag',
    'Compass Group Plc',
    'Muenchener Rueckver Ag-Reg',
    'Linde Ag',
    'Aon Plc',
    'Actelion Ltd-Reg',
    'Liberty Global Plc-A',
]

def criar_empresas():
    from empresa.models import Empresa
    from usuario.models import Usuario

    for empresa in lista_empresas:
        nome = lista_nomes[randint(0, 10000)]

        emp = Empresa.objects.create(
            cpf_cnpj=randint(10000000000000, 99999999999999),
            razao_social=f'{empresa} LTDA',
            nome_fantasia=empresa,
            logradouro=f'{lista_logradouro[randint(0, 2)]} {nome}',
            numero=randint(1, 99999),
            bairro=nome[len(nome) - 1],
            municipio='Município',
            uf=UF_CHOICES[len(UF_CHOICES) -1][0],
            cep=randint(10000000, 99999999),
            telefone=randint(1000000000, 9999999999)
        )

        for index, nome_pessoa in enumerate(lista_nomes):
            Usuario.objects.create(
                username=f"{nome_pessoa.replace(' ', '_', 100)}_{emp.id}{index}",
                password=randint(1000, 9999),
                codigo_verificacao_segunda_etapa=randint(1000, 9999),
                telefone=emp.telefone,
                empresa=emp
            )
