from django_filters import rest_framework as filter
from .models import Ticket, MensagemTicket
from usuario.filters import lookup_types_usuario
from empresa.filters import lookup_types_empresa

lookup_types_ticket = {
    'uuid': ['exact', 'in', ],
    'codigo': ['exact', 'contains', 'gt', 'gte', 'lt', 'lte', 'in', 'range'],
    'status': ['exact', 'iexact', 'icontains', 'istartswith', 'iendswith', 'in', 'iregex', ],
    'solicitante': ['exact', ],
    'atendente': ['exact', ],
    'data_atribuicao_atendente': [
        'exact',
        'range',
        'year', 'year__gte', 'year__gt', 'year__lte', 'year__lt', 'year__range', 'year__in',
        'month', 'month__gte', 'month__gt', 'month__lte', 'month__lt', 'month__range', 'month__in',
        'day', 'day__gte', 'day__gt', 'day__lte', 'day__lt', 'day__range', 'day__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
    'hora_atribuicao_atendente': [
        'exact',
        'range',
        'hour', 'hour__gte', 'hour__gt', 'hour__lte', 'hour__lt', 'hour__range', 'hour__in',
        'minute', 'minute__gte', 'minute__gt', 'minute__lte', 'minute__lt', 'minute__range', 'minute__in',
        'second', 'second__gte', 'second__gt', 'second__lte', 'second__lt', 'second__range', 'second__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
    'titulo': ['exact', 'iexact', 'icontains', 'istartswith', 'iendswith', 'in', 'iregex', ],
    'descricao': ['exact', 'iexact', 'icontains', 'istartswith', 'iendswith', 'in', 'iregex', ],
    'solucionado': ['exact', ],
    'data_solucao': [
        'exact',
        'range',
        'year', 'year__gte', 'year__gt', 'year__lte', 'year__lt', 'year__range', 'year__in',
        'month', 'month__gte', 'month__gt', 'month__lte', 'month__lt', 'month__range', 'month__in',
        'day', 'day__gte', 'day__gt', 'day__lte', 'day__lt', 'day__range', 'day__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
    'hora_solucao': [
        'exact',
        'range',
        'hour', 'hour__gte', 'hour__gt', 'hour__lte', 'hour__lt', 'hour__range', 'hour__in',
        'minute', 'minute__gte', 'minute__gt', 'minute__lte', 'minute__lt', 'minute__range', 'minute__in',
        'second', 'second__gte', 'second__gt', 'second__lte', 'second__lt', 'second__range', 'second__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
    'finalizado': ['exact', ],
    'data_finalizacao': [
        'exact',
        'range',
        'year', 'year__gte', 'year__gt', 'year__lte', 'year__lt', 'year__range', 'year__in',
        'month', 'month__gte', 'month__gt', 'month__lte', 'month__lt', 'month__range', 'month__in',
        'day', 'day__gte', 'day__gt', 'day__lte', 'day__lt', 'day__range', 'day__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
    'hora_finalizacao': [
        'exact',
        'range',
        'hour', 'hour__gte', 'hour__gt', 'hour__lte', 'hour__lt', 'hour__range', 'hour__in',
        'minute', 'minute__gte', 'minute__gt', 'minute__lte', 'minute__lt', 'minute__range', 'minute__in',
        'second', 'second__gte', 'second__gt', 'second__lte', 'second__lt', 'second__range', 'second__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
    'cancelado': ['exact', ],
    'motivo_cancelamento': ['exact', 'iexact', 'icontains', 'istartswith', 'iendswith', 'in', 'iregex', ],
    'data_cancelamento': [
        'exact',
        'range',
        'year', 'year__gte', 'year__gt', 'year__lte', 'year__lt', 'year__range', 'year__in',
        'month', 'month__gte', 'month__gt', 'month__lte', 'month__lt', 'month__range', 'month__in',
        'day', 'day__gte', 'day__gt', 'day__lte', 'day__lt', 'day__range', 'day__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
    'hora_cancelamento': [
        'exact',
        'range',
        'hour', 'hour__gte', 'hour__gt', 'hour__lte', 'hour__lt', 'hour__range', 'hour__in',
        'minute', 'minute__gte', 'minute__gt', 'minute__lte', 'minute__lt', 'minute__range', 'minute__in',
        'second', 'second__gte', 'second__gt', 'second__lte', 'second__lt', 'second__range', 'second__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
    'avaliacao_solicitante': [
        'exact',
        'iexact',
        'icontains',
        'istartswith',
        'iendswith',
        'in',
        'range',
        'gte',
        'lte',
        'gt',
        'lt',
    ],
    'data_cadastro': [
        'exact',
        'range',
        'year', 'year__gte', 'year__gt', 'year__lte', 'year__lt', 'year__range', 'year__in',
        'month', 'month__gte', 'month__gt', 'month__lte', 'month__lt', 'month__range', 'month__in',
        'day', 'day__gte', 'day__gt', 'day__lte', 'day__lt', 'day__range', 'day__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
    'hora_cadastro': [
        'exact',
        'range',
        'hour', 'hour__gte', 'hour__gt', 'hour__lte', 'hour__lt', 'hour__range', 'hour__in',
        'minute', 'minute__gte', 'minute__gt', 'minute__lte', 'minute__lt', 'minute__range', 'minute__in',
        'second', 'second__gte', 'second__gt', 'second__lte', 'second__lt', 'second__range', 'second__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
}

lookup_types_mensagem_ticket = {
    'uuid': ['exact', 'in', ],
    'usuario': ['exact', ],
    'ticket': ['exact', ],
    'mensagem': ['exact', 'iexact', 'icontains', 'istartswith', 'iendswith', 'in', 'iregex', ],
    'mensagem_relacionada': ['exact', ],
    'solucao': ['iexact', ],
    'data_cadastro': [
        'exact',
        'range',
        'year', 'year__gte', 'year__gt', 'year__lte', 'year__lt', 'year__range', 'year__in',
        'month', 'month__gte', 'month__gt', 'month__lte', 'month__lt', 'month__range', 'month__in',
        'day', 'day__gte', 'day__gt', 'day__lte', 'day__lt', 'day__range', 'day__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
    'hora_cadastro': [
        'exact',
        'range',
        'hour', 'hour__gte', 'hour__gt', 'hour__lte', 'hour__lt', 'hour__range', 'hour__in',
        'minute', 'minute__gte', 'minute__gt', 'minute__lte', 'minute__lt', 'minute__range', 'minute__in',
        'second', 'second__gte', 'second__gt', 'second__lte', 'second__lt', 'second__range', 'second__in',
        'gte',
        'gt',
        'lte',
        'lt',
        'in',
    ],
}


class TicketFilter(filter.FilterSet):
    class Meta:
        model = Ticket
        fields = {
            'uuid': lookup_types_ticket['uuid'],
            'codigo': lookup_types_ticket['codigo'],
            'status': lookup_types_ticket['status'],
            'solicitante': lookup_types_ticket['solicitante'],
            'solicitante__uuid': lookup_types_usuario['uuid'],
            #'solicitante__codigo': lookup_types_usuario['codigo'],
            'solicitante__username': lookup_types_usuario['username'],
            'solicitante__first_name': lookup_types_usuario['first_name'],
            'solicitante__last_name': lookup_types_usuario['last_name'],
            'solicitante__email': lookup_types_usuario['email'],
            'solicitante__telefone': lookup_types_usuario['telefone'],
            'solicitante__celular': lookup_types_usuario['celular'],
            'solicitante__observacoes': lookup_types_usuario['observacoes'],
            'solicitante__media_avaliacoes': lookup_types_usuario['media_avaliacoes'],
            'solicitante__empresa': lookup_types_usuario['empresa'],
            'solicitante__empresa__uuid': lookup_types_empresa['uuid'],
            'solicitante__empresa__codigo': lookup_types_empresa['codigo'],
            'solicitante__empresa__cpf_cnpj': lookup_types_empresa['cpf_cnpj'],
            'solicitante__empresa__razao_social': lookup_types_empresa['razao_social'],
            'solicitante__empresa__nome_fantasia': lookup_types_empresa['nome_fantasia'],
            'solicitante__empresa__logradouro': lookup_types_empresa['logradouro'],
            'solicitante__empresa__numero': lookup_types_empresa['numero'],
            'solicitante__empresa__complemento': lookup_types_empresa['complemento'],
            'solicitante__empresa__bairro': lookup_types_empresa['bairro'],
            'solicitante__empresa__municipio': lookup_types_empresa['municipio'],
            'solicitante__empresa__uf': lookup_types_empresa['uf'],
            'solicitante__empresa__cep': lookup_types_empresa['cep'],
            'solicitante__empresa__pais': lookup_types_empresa['pais'],
            'solicitante__empresa__telefone': lookup_types_empresa['telefone'],
            'solicitante__empresa__media_avaliacoes': lookup_types_empresa['media_avaliacoes'],
            'solicitante__empresa__prestadora_servico': lookup_types_empresa['prestadora_servico'],
            'solicitante__empresa__ativo': lookup_types_empresa['ativo'],
            'solicitante__last_login': lookup_types_usuario['last_login'],
            'solicitante__is_staff': lookup_types_usuario['is_staff'],
            'solicitante__is_manager': lookup_types_usuario['is_manager'],
            'solicitante__is_superuser': lookup_types_usuario['is_superuser'],
            'solicitante__is_active': lookup_types_usuario['is_active'],
            'solicitante__groups': lookup_types_usuario['groups'],
            'atendente': lookup_types_ticket['atendente'],
            'atendente__uuid': lookup_types_usuario['uuid'],
            #'atendente__codigo': lookup_types_usuario['codigo'],
            'atendente__username': lookup_types_usuario['username'],
            'atendente__first_name': lookup_types_usuario['first_name'],
            'atendente__last_name': lookup_types_usuario['last_name'],
            'atendente__email': lookup_types_usuario['email'],
            'atendente__telefone': lookup_types_usuario['telefone'],
            'atendente__celular': lookup_types_usuario['celular'],
            'atendente__observacoes': lookup_types_usuario['observacoes'],
            'atendente__media_avaliacoes': lookup_types_usuario['media_avaliacoes'],
            'atendente__empresa': lookup_types_usuario['empresa'],
            'atendente__empresa__uuid': lookup_types_empresa['uuid'],
            'atendente__empresa__codigo': lookup_types_empresa['codigo'],
            'atendente__empresa__cpf_cnpj': lookup_types_empresa['cpf_cnpj'],
            'atendente__empresa__razao_social': lookup_types_empresa['razao_social'],
            'atendente__empresa__nome_fantasia': lookup_types_empresa['nome_fantasia'],
            'atendente__empresa__logradouro': lookup_types_empresa['logradouro'],
            'atendente__empresa__numero': lookup_types_empresa['numero'],
            'atendente__empresa__complemento': lookup_types_empresa['complemento'],
            'atendente__empresa__bairro': lookup_types_empresa['bairro'],
            'atendente__empresa__municipio': lookup_types_empresa['municipio'],
            'atendente__empresa__uf': lookup_types_empresa['uf'],
            'atendente__empresa__cep': lookup_types_empresa['cep'],
            'atendente__empresa__pais': lookup_types_empresa['pais'],
            'atendente__empresa__telefone': lookup_types_empresa['telefone'],
            'atendente__empresa__media_avaliacoes': lookup_types_empresa['media_avaliacoes'],
            'atendente__empresa__prestadora_servico': lookup_types_empresa['prestadora_servico'],
            'atendente__empresa__ativo': lookup_types_empresa['ativo'],
            'atendente__last_login': lookup_types_usuario['last_login'],
            'atendente__is_staff': lookup_types_usuario['is_staff'],
            'atendente__is_manager': lookup_types_usuario['is_manager'],
            'atendente__is_superuser': lookup_types_usuario['is_superuser'],
            'atendente__is_active': lookup_types_usuario['is_active'],
            'atendente__groups': lookup_types_usuario['groups'],
            'data_atribuicao_atendente': lookup_types_ticket['data_atribuicao_atendente'],
            'hora_atribuicao_atendente': lookup_types_ticket['hora_atribuicao_atendente'],
            'titulo': lookup_types_ticket['titulo'],
            'descricao': lookup_types_ticket['descricao'],
            'solucionado': lookup_types_ticket['solucionado'],
            'solucionado__uuid': lookup_types_mensagem_ticket['uuid'],
            'solucionado__usuario': lookup_types_mensagem_ticket['usuario'],
            'solucionado__usuario__uuid': lookup_types_usuario['uuid'],
            #'solucionado__usuario__codigo': lookup_types_usuario['codigo'],
            'solucionado__usuario__username': lookup_types_usuario['username'],
            'solucionado__usuario__first_name': lookup_types_usuario['first_name'],
            'solucionado__usuario__last_name': lookup_types_usuario['last_name'],
            'solucionado__usuario__email': lookup_types_usuario['email'],
            'solucionado__usuario__telefone': lookup_types_usuario['telefone'],
            'solucionado__usuario__celular': lookup_types_usuario['celular'],
            'solucionado__usuario__observacoes': lookup_types_usuario['observacoes'],
            'solucionado__usuario__media_avaliacoes': lookup_types_usuario['media_avaliacoes'],
            'solucionado__usuario__empresa': lookup_types_usuario['empresa'],
            'solucionado__usuario__empresa__uuid': lookup_types_empresa['uuid'],
            'solucionado__usuario__empresa__codigo': lookup_types_empresa['codigo'],
            'solucionado__usuario__empresa__cpf_cnpj': lookup_types_empresa['cpf_cnpj'],
            'solucionado__usuario__empresa__razao_social': lookup_types_empresa['razao_social'],
            'solucionado__usuario__empresa__nome_fantasia': lookup_types_empresa['nome_fantasia'],
            'solucionado__usuario__empresa__logradouro': lookup_types_empresa['logradouro'],
            'solucionado__usuario__empresa__numero': lookup_types_empresa['numero'],
            'solucionado__usuario__empresa__complemento': lookup_types_empresa['complemento'],
            'solucionado__usuario__empresa__bairro': lookup_types_empresa['bairro'],
            'solucionado__usuario__empresa__municipio': lookup_types_empresa['municipio'],
            'solucionado__usuario__empresa__uf': lookup_types_empresa['uf'],
            'solucionado__usuario__empresa__cep': lookup_types_empresa['cep'],
            'solucionado__usuario__empresa__pais': lookup_types_empresa['pais'],
            'solucionado__usuario__empresa__telefone': lookup_types_empresa['telefone'],
            'solucionado__usuario__empresa__media_avaliacoes': lookup_types_empresa['media_avaliacoes'],
            'solucionado__usuario__empresa__prestadora_servico': lookup_types_empresa['prestadora_servico'],
            'solucionado__usuario__empresa__ativo': lookup_types_empresa['ativo'],
            'solucionado__usuario__last_login': lookup_types_usuario['last_login'],
            'solucionado__usuario__is_staff': lookup_types_usuario['is_staff'],
            'solucionado__usuario__is_manager': lookup_types_usuario['is_manager'],
            'solucionado__usuario__is_superuser': lookup_types_usuario['is_superuser'],
            'solucionado__usuario__is_active': lookup_types_usuario['is_active'],
            'solucionado__usuario__groups': lookup_types_usuario['groups'],
            'solucionado__mensagem': lookup_types_mensagem_ticket['mensagem'],
            'solucionado__solucao': lookup_types_mensagem_ticket['solucao'],
            'solucionado__data_cadastro': lookup_types_mensagem_ticket['data_cadastro'],
            'solucionado__hora_cadastro': lookup_types_mensagem_ticket['hora_cadastro'],
            'data_solucao': lookup_types_ticket['data_solucao'],
            'hora_solucao': lookup_types_ticket['hora_solucao'],
            'finalizado': lookup_types_ticket['finalizado'],
            'finalizado__uuid': lookup_types_usuario['uuid'],
            #'finalizado__codigo': lookup_types_usuario['codigo'],
            'finalizado__username': lookup_types_usuario['username'],
            'finalizado__first_name': lookup_types_usuario['first_name'],
            'finalizado__last_name': lookup_types_usuario['last_name'],
            'finalizado__email': lookup_types_usuario['email'],
            'finalizado__telefone': lookup_types_usuario['telefone'],
            'finalizado__celular': lookup_types_usuario['celular'],
            'finalizado__observacoes': lookup_types_usuario['observacoes'],
            'finalizado__media_avaliacoes': lookup_types_usuario['media_avaliacoes'],
            'finalizado__empresa': lookup_types_usuario['empresa'],
            'finalizado__empresa__uuid': lookup_types_empresa['uuid'],
            'finalizado__empresa__codigo': lookup_types_empresa['codigo'],
            'finalizado__empresa__cpf_cnpj': lookup_types_empresa['cpf_cnpj'],
            'finalizado__empresa__razao_social': lookup_types_empresa['razao_social'],
            'finalizado__empresa__nome_fantasia': lookup_types_empresa['nome_fantasia'],
            'finalizado__empresa__logradouro': lookup_types_empresa['logradouro'],
            'finalizado__empresa__numero': lookup_types_empresa['numero'],
            'finalizado__empresa__complemento': lookup_types_empresa['complemento'],
            'finalizado__empresa__bairro': lookup_types_empresa['bairro'],
            'finalizado__empresa__municipio': lookup_types_empresa['municipio'],
            'finalizado__empresa__uf': lookup_types_empresa['uf'],
            'finalizado__empresa__cep': lookup_types_empresa['cep'],
            'finalizado__empresa__pais': lookup_types_empresa['pais'],
            'finalizado__empresa__telefone': lookup_types_empresa['telefone'],
            'finalizado__empresa__media_avaliacoes': lookup_types_empresa['media_avaliacoes'],
            'finalizado__empresa__prestadora_servico': lookup_types_empresa['prestadora_servico'],
            'finalizado__empresa__ativo': lookup_types_empresa['ativo'],
            'finalizado__last_login': lookup_types_usuario['last_login'],
            'finalizado__is_staff': lookup_types_usuario['is_staff'],
            'finalizado__is_manager': lookup_types_usuario['is_manager'],
            'finalizado__is_superuser': lookup_types_usuario['is_superuser'],
            'finalizado__is_active': lookup_types_usuario['is_active'],
            'finalizado__groups': lookup_types_usuario['groups'],
            'data_finalizacao': lookup_types_ticket['data_finalizacao'],
            'hora_finalizacao': lookup_types_ticket['hora_finalizacao'],
            'cancelado': lookup_types_ticket['cancelado'],
            'cancelado__uuid': lookup_types_usuario['uuid'],
            #'cancelado__codigo': lookup_types_usuario['codigo'],
            'cancelado__username': lookup_types_usuario['username'],
            'cancelado__first_name': lookup_types_usuario['first_name'],
            'cancelado__last_name': lookup_types_usuario['last_name'],
            'cancelado__email': lookup_types_usuario['email'],
            'cancelado__telefone': lookup_types_usuario['telefone'],
            'cancelado__celular': lookup_types_usuario['celular'],
            'cancelado__observacoes': lookup_types_usuario['observacoes'],
            'cancelado__media_avaliacoes': lookup_types_usuario['media_avaliacoes'],
            'cancelado__empresa': lookup_types_usuario['empresa'],
            'cancelado__empresa__uuid': lookup_types_empresa['uuid'],
            'cancelado__empresa__codigo': lookup_types_empresa['codigo'],
            'cancelado__empresa__cpf_cnpj': lookup_types_empresa['cpf_cnpj'],
            'cancelado__empresa__razao_social': lookup_types_empresa['razao_social'],
            'cancelado__empresa__nome_fantasia': lookup_types_empresa['nome_fantasia'],
            'cancelado__empresa__logradouro': lookup_types_empresa['logradouro'],
            'cancelado__empresa__numero': lookup_types_empresa['numero'],
            'cancelado__empresa__complemento': lookup_types_empresa['complemento'],
            'cancelado__empresa__bairro': lookup_types_empresa['bairro'],
            'cancelado__empresa__municipio': lookup_types_empresa['municipio'],
            'cancelado__empresa__uf': lookup_types_empresa['uf'],
            'cancelado__empresa__cep': lookup_types_empresa['cep'],
            'cancelado__empresa__pais': lookup_types_empresa['pais'],
            'cancelado__empresa__telefone': lookup_types_empresa['telefone'],
            'cancelado__empresa__media_avaliacoes': lookup_types_empresa['media_avaliacoes'],
            'cancelado__empresa__prestadora_servico': lookup_types_empresa['prestadora_servico'],
            'cancelado__empresa__ativo': lookup_types_empresa['ativo'],
            'cancelado__last_login': lookup_types_usuario['last_login'],
            'cancelado__is_staff': lookup_types_usuario['is_staff'],
            'cancelado__is_manager': lookup_types_usuario['is_manager'],
            'cancelado__is_superuser': lookup_types_usuario['is_superuser'],
            'cancelado__is_active': lookup_types_usuario['is_active'],
            'cancelado__groups': lookup_types_usuario['groups'],
            'motivo_cancelamento': lookup_types_ticket['motivo_cancelamento'],
            'data_cancelamento': lookup_types_ticket['data_cancelamento'],
            'hora_cancelamento': lookup_types_ticket['hora_cancelamento'],
            'avaliacao_solicitante': lookup_types_ticket['avaliacao_solicitante'],
            'data_cadastro': lookup_types_ticket['data_cadastro'],
            'hora_cadastro': lookup_types_ticket['hora_cadastro'],
        }


class MensagemTicketFilter(filter.FilterSet):
    class Meta:
        model = MensagemTicket
        fields = {
            'uuid': lookup_types_mensagem_ticket['uuid'],
            'usuario': lookup_types_mensagem_ticket['usuario'],
            'usuario__uuid': lookup_types_usuario['uuid'],
            #'usuario__codigo': lookup_types_usuario['codigo'],
            'usuario__username': lookup_types_usuario['username'],
            'usuario__first_name': lookup_types_usuario['first_name'],
            'usuario__last_name': lookup_types_usuario['last_name'],
            'usuario__email': lookup_types_usuario['email'],
            'usuario__telefone': lookup_types_usuario['telefone'],
            'usuario__celular': lookup_types_usuario['celular'],
            'usuario__observacoes': lookup_types_usuario['observacoes'],
            'usuario__media_avaliacoes': lookup_types_usuario['media_avaliacoes'],
            'usuario__empresa': lookup_types_usuario['empresa'],
            'usuario__empresa__uuid': lookup_types_empresa['uuid'],
            'usuario__empresa__codigo': lookup_types_empresa['codigo'],
            'usuario__empresa__cpf_cnpj': lookup_types_empresa['cpf_cnpj'],
            'usuario__empresa__razao_social': lookup_types_empresa['razao_social'],
            'usuario__empresa__nome_fantasia': lookup_types_empresa['nome_fantasia'],
            'usuario__empresa__logradouro': lookup_types_empresa['logradouro'],
            'usuario__empresa__numero': lookup_types_empresa['numero'],
            'usuario__empresa__complemento': lookup_types_empresa['complemento'],
            'usuario__empresa__bairro': lookup_types_empresa['bairro'],
            'usuario__empresa__municipio': lookup_types_empresa['municipio'],
            'usuario__empresa__uf': lookup_types_empresa['uf'],
            'usuario__empresa__cep': lookup_types_empresa['cep'],
            'usuario__empresa__pais': lookup_types_empresa['pais'],
            'usuario__empresa__telefone': lookup_types_empresa['telefone'],
            'usuario__empresa__media_avaliacoes': lookup_types_empresa['media_avaliacoes'],
            'usuario__empresa__prestadora_servico': lookup_types_empresa['prestadora_servico'],
            'usuario__empresa__ativo': lookup_types_empresa['ativo'],
            'usuario__last_login': lookup_types_usuario['last_login'],
            'usuario__is_staff': lookup_types_usuario['is_staff'],
            'usuario__is_manager': lookup_types_usuario['is_manager'],
            'usuario__is_superuser': lookup_types_usuario['is_superuser'],
            'usuario__is_active': lookup_types_usuario['is_active'],
            'usuario__groups': lookup_types_usuario['groups'],
            'ticket': lookup_types_mensagem_ticket['ticket'],
            'ticket__uuid': lookup_types_ticket['uuid'],
            'ticket__codigo': lookup_types_ticket['codigo'],
            'ticket__status': lookup_types_ticket['status'],
            'ticket__solicitante': lookup_types_ticket['solicitante'],
            'ticket__solicitante__uuid': lookup_types_usuario['uuid'],
            #'ticket__solicitante__codigo': lookup_types_usuario['codigo'],
            'ticket__solicitante__username': lookup_types_usuario['username'],
            'ticket__solicitante__first_name': lookup_types_usuario['first_name'],
            'ticket__solicitante__last_name': lookup_types_usuario['last_name'],
            'ticket__solicitante__email': lookup_types_usuario['email'],
            'ticket__solicitante__telefone': lookup_types_usuario['telefone'],
            'ticket__solicitante__celular': lookup_types_usuario['celular'],
            'ticket__solicitante__observacoes': lookup_types_usuario['observacoes'],
            'ticket__solicitante__media_avaliacoes': lookup_types_usuario['media_avaliacoes'],
            'ticket__solicitante__empresa': lookup_types_usuario['empresa'],
            'ticket__solicitante__empresa__uuid': lookup_types_empresa['uuid'],
            'ticket__solicitante__empresa__codigo': lookup_types_empresa['codigo'],
            'ticket__solicitante__empresa__cpf_cnpj': lookup_types_empresa['cpf_cnpj'],
            'ticket__solicitante__empresa__razao_social': lookup_types_empresa['razao_social'],
            'ticket__solicitante__empresa__nome_fantasia': lookup_types_empresa['nome_fantasia'],
            'ticket__solicitante__empresa__logradouro': lookup_types_empresa['logradouro'],
            'ticket__solicitante__empresa__numero': lookup_types_empresa['numero'],
            'ticket__solicitante__empresa__complemento': lookup_types_empresa['complemento'],
            'ticket__solicitante__empresa__bairro': lookup_types_empresa['bairro'],
            'ticket__solicitante__empresa__municipio': lookup_types_empresa['municipio'],
            'ticket__solicitante__empresa__uf': lookup_types_empresa['uf'],
            'ticket__solicitante__empresa__cep': lookup_types_empresa['cep'],
            'ticket__solicitante__empresa__pais': lookup_types_empresa['pais'],
            'ticket__solicitante__empresa__telefone': lookup_types_empresa['telefone'],
            'ticket__solicitante__empresa__media_avaliacoes': lookup_types_empresa['media_avaliacoes'],
            'ticket__solicitante__empresa__prestadora_servico': lookup_types_empresa['prestadora_servico'],
            'ticket__solicitante__empresa__ativo': lookup_types_empresa['ativo'],
            'ticket__solicitante__last_login': lookup_types_usuario['last_login'],
            'ticket__solicitante__is_staff': lookup_types_usuario['is_staff'],
            'ticket__solicitante__is_manager': lookup_types_usuario['is_manager'],
            'ticket__solicitante__is_superuser': lookup_types_usuario['is_superuser'],
            'ticket__solicitante__is_active': lookup_types_usuario['is_active'],
            'ticket__solicitante__groups': lookup_types_usuario['groups'],
            'ticket__atendente': lookup_types_ticket['atendente'],
            'ticket__atendente__uuid': lookup_types_usuario['uuid'],
            #'ticket__atendente__codigo': lookup_types_usuario['codigo'],
            'ticket__atendente__username': lookup_types_usuario['username'],
            'ticket__atendente__first_name': lookup_types_usuario['first_name'],
            'ticket__atendente__last_name': lookup_types_usuario['last_name'],
            'ticket__atendente__email': lookup_types_usuario['email'],
            'ticket__atendente__telefone': lookup_types_usuario['telefone'],
            'ticket__atendente__celular': lookup_types_usuario['celular'],
            'ticket__atendente__observacoes': lookup_types_usuario['observacoes'],
            'ticket__atendente__media_avaliacoes': lookup_types_usuario['media_avaliacoes'],
            'ticket__atendente__empresa': lookup_types_usuario['empresa'],
            'ticket__atendente__empresa__uuid': lookup_types_empresa['uuid'],
            'ticket__atendente__empresa__cpf_cnpj': lookup_types_empresa['cpf_cnpj'],
            'ticket__atendente__empresa__razao_social': lookup_types_empresa['razao_social'],
            'ticket__atendente__empresa__nome_fantasia': lookup_types_empresa['nome_fantasia'],
            'ticket__atendente__empresa__logradouro': lookup_types_empresa['logradouro'],
            'ticket__atendente__empresa__numero': lookup_types_empresa['numero'],
            'ticket__atendente__empresa__complemento': lookup_types_empresa['complemento'],
            'ticket__atendente__empresa__bairro': lookup_types_empresa['bairro'],
            'ticket__atendente__empresa__municipio': lookup_types_empresa['municipio'],
            'ticket__atendente__empresa__uf': lookup_types_empresa['uf'],
            'ticket__atendente__empresa__cep': lookup_types_empresa['cep'],
            'ticket__atendente__empresa__pais': lookup_types_empresa['pais'],
            'ticket__atendente__empresa__telefone': lookup_types_empresa['telefone'],
            'ticket__atendente__empresa__media_avaliacoes': lookup_types_empresa['media_avaliacoes'],
            'ticket__atendente__empresa__prestadora_servico': lookup_types_empresa['prestadora_servico'],
            'ticket__atendente__empresa__ativo': lookup_types_empresa['ativo'],
            'ticket__atendente__last_login': lookup_types_usuario['last_login'],
            'ticket__atendente__is_staff': lookup_types_usuario['is_staff'],
            'ticket__atendente__is_manager': lookup_types_usuario['is_manager'],
            'ticket__atendente__is_superuser': lookup_types_usuario['is_superuser'],
            'ticket__atendente__is_active': lookup_types_usuario['is_active'],
            'ticket__atendente__groups': lookup_types_usuario['groups'],
            'ticket__data_atribuicao_atendente': lookup_types_ticket['data_atribuicao_atendente'],
            'ticket__hora_atribuicao_atendente': lookup_types_ticket['hora_atribuicao_atendente'],
            'ticket__titulo': lookup_types_ticket['titulo'],
            'ticket__descricao': lookup_types_ticket['descricao'],
            'ticket__avaliacao_solicitante': lookup_types_ticket['avaliacao_solicitante'],
            'ticket__data_cadastro': lookup_types_ticket['data_cadastro'],
            'ticket__hora_cadastro': lookup_types_ticket['hora_cadastro'],
            'mensagem': lookup_types_mensagem_ticket['mensagem'],
            'solucao': lookup_types_mensagem_ticket['solucao'],
            'data_cadastro': lookup_types_mensagem_ticket['data_cadastro'],
            'hora_cadastro': lookup_types_mensagem_ticket['hora_cadastro'],
        }
